version: '3.8'
services:
  acma-iam-config-service:
    container_name: acma-iam-workforce-db
    image: mysql:latest
    restart: on-failure
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=acma-iam-workforce-kc-db
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - acma-iam-network
    volumes:
      - /Users/dhruvkumar/Documents/Documents - Dhruv’s MacBook Air/Narsi_jrtp/ACMA/resource/acma-resources/keycloak-docker-compose/acma-workforce-db:/var/lib/mysql

  acma-iam-fed-service:
    container_name: acma-customer-ldap
    image: openidentityplatform/opendj:latest
    restart: on-failure
    ports:
      - 1388:1389
      - 1636:1636
      - 4444:4444
    environment:
      - BASE_DN=dc=acma,dc=com
      - ROOT_USER_DN=uid=acmaadmin
      - ROOT_PASSWORD=acmaadmin
    networks:
      - acma-iam-network
    volumes:
      - /Users/dhruvkumar/Documents/Documents - Dhruv’s MacBook Air/Narsi_jrtp/ACMA/resource/acma-resources/keycloak-docker-compose/acma-ldap-db:/opt/opendj/data

  acma-iam-keycloak-service:
    container_name: acma-iam-keycloak
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    restart: always
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 0"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://acma-iam-config-service/acma-iam-workforce-kc-db
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    depends_on:
      - acma-iam-config-service
      - acma-iam-fed-service
    networks:
      - acma-iam-network
  acma-authnz-service:
    container_name: acma-authnz-svc
    build: '/Users/dhruvkumar/Documents/Documents - Dhruv’s MacBook Air/Narsi_jrtp/ACMA/source-code/agent-customer-market-analyzer/acma-authnz-svc'
    ports:
      - 5052:5052
    environment:
      - IAM_USERS_HOST=acma-iam-keycloak-service
      - IAM_USERS_PORT=8080
      - IAM_PROTOCOL=http
      - IAM_REALMS=acma
      - ACMA_IDP=keycloak
      - ACMA_IDP_CLIENT_ID=statefarm-code-svc
      - ACMA_IDP_CLIENT_SECRET=QhIRv6jNrcX2KhR6Ewcij3oB08BJsTcE
      - ACMA_IODC__GRANT_TYPE=authorization_code
      - IAM_PROTOCOL=http
      - IAM_HOST=acma-iam-keycloak
      - IAM_PORT=8080
      - IAM_REALMS=acma
      - ACMA_CACHE_HOST=acma-redis-stack
      - ACMA_CACHE_PORT=6379
      - ACMA_CACHE_PASSWORD=admin
      - ACMA_CACHE_USERNAME=admin
      - ACMA_REGISTRY_PROTOCOL=http
      - ACMA_REGISTRY_HOSTNAME=acma-registry-server
      - ACMA_REGISTRY_PORT=8761
      - ACMA_AUTHNZ_PORT=5052
      - ACMA_AUTHNZ_PROFILE=dev
    depends_on:
      acma-iam-keycloak-service:
        condition: service_healthy
      acma-registry-server-svc:
        condition: service_healthy
    networks:
      - acma-iam-network
#      - acma-shared-network

  acma-registry-server-svc:
    container_name: acma-registry-server
    build: '/Users/dhruvkumar/Documents/Documents - Dhruv’s MacBook Air/Narsi_jrtp/ACMA/source-code/agent-customer-market-analyzer/acma-registry-svr'
    ports:
      - 8761:8761
    environment:
      - ACMA-REGISTRY_PORT=8761
    healthcheck:
      test: "curl --fail --silent http://acma-registry-server:8761/actuator/health/readiness | grep UP || exit 0"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - acma-iam-network
#      - acma-shared-network

  acma-redis-stack-service:
    image: redis/redis-stack:latest
    container_name: acma-redis-stack
    restart: on-failure
    environment:
#      REDIS_ARGS: "--requirepass root"
      REDIS_ARGS: "--requirepass admin --user admin on >admin ~* allcommands --user default off nopass nocommands"
    volumes:
      - ./keycloak-docker-compose/redis-cache:/data
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - acma-iam-network
#      - acma-shared-network
  acma-cache-client-service:
    image: redis/redisinsight:latest
    container_name: acma-cache-client
    restart: on-failure
    ports:
      - 5539:5540
    networks:
      - acma-iam-network

networks:
  acma-iam-network:
    driver: bridge
#  acma-shared-network:
#    external: true